### ISSUE TITLE
Robust Finger movements

### ISSUE THREAD

**Issue by floweisshardt** [ipa320/hmi_2015#25] opened 2015-03-27 00:14 UTC
One click one move (each command should move the gripper)

clamping

Emergency and recover

**Comment by fmessmer** [comment] 2015-04-15 14:13
The grippers mainly failed as soon as a Cartesian path (planned by MoveIt!) is being executed.
Reducing the `eef_step` parameter "solved" the problem for know.

Thus, I think the problem is not mainly related to temperature, but might be related to jerky motion and a firmware reboot...as the duration until the gripper is able to be moved again is almost always the same and the movements of compute_cartesian_path are somewhat jerky due to the hardcoded 0.2 duration per trajectory point....

Still needs further investigation!

**Comment by fmessmer** [comment] 2015-04-20 06:14
also see https://github.com/ipa320/cob4/issues/183

**Comment by fmessmer** [comment] 2015-09-04 19:37
Wontfix within hmi2015

**Closed as completed by fmessmer** 2015-09-04 19:37 UTC
Labels: bug, wontfix
